
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - replication.storage.ramen.io
  resources:
  - volumereplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replication.storage.ramen.io
  resources:
  - volumereplications/finalizers
  verbs:
  - update
- apiGroups:
  - replication.storage.ramen.io
  resources:
  - volumereplications/status
  verbs:
  - get
  - patch
  - update
